name: start project
on: push
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-node@v18
        - uses: actions/setup-npm@v6
        - uses: actions/setup-make
        - name: run tests
          run: make setup
          run: make start
        - name: run tests
          run: make test
        - name: run linter
          run: make lint
