name: start project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - run: npm install
      - run: malefile install
      - name: run tests
        run: make setup
      - name: run tests
        run: make test
      - name: run linter
        run: make lint
