name: start project
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - run: make setup
        - run: make start
        test:
          - run: make test
          - run: make lint
