name: start project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm install -g bats
      - run: make build
      - name: run tests
        run: make setup
      - name: run tests
        run: make test
      - name: run linter
        run: make lint
