name: start project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/update-node@v18
      - run: npm install
      - run: makefile install
      - name: run tests
        run: make setup
      - name: run tests
        run: make test
      - name: run linter
        run: make lint
